// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunction = "functions"

// Function mapped from table <functions>
type Function struct {
	FunctionID    int64  `gorm:"column:function_id;type:bigint;primaryKey;autoIncrement:true;comment:函数主键" json:"function_id"`
	FunctionLabel string `gorm:"column:function_label;type:varchar(128);not null;comment:函数名称" json:"function_label"`
	UserID        int64  `gorm:"column:user_id;type:bigint;not null;comment:所属用户的id" json:"user_id"`
	TriggerID     int64  `gorm:"column:trigger_id;type:bigint;not null;comment:触发器的id" json:"trigger_id"`
	SrcType       string `gorm:"column:src_type;type:varchar(32);not null;comment:源代码导入方式" json:"src_type"`
	SrcLoc        string `gorm:"column:src_loc;type:varchar(256);not null;comment:代码定位数据" json:"src_loc"`
	Replicas      int32  `gorm:"column:replicas;type:int;not null;default:1;comment:副本数" json:"replicas"`
	QuotaInfo     string `gorm:"column:quota_info;type:text;not null;comment:配额信息" json:"quota_info"`
	TemplateID    int64  `gorm:"column:template_id;type:bigint;not null;comment:模板ID" json:"template_id"`
}

// TableName Function's table name
func (*Function) TableName() string {
	return TableNameFunction
}
