// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTemplate = "templates"

// Template mapped from table <templates>
type Template struct {
	TemplateID    int64  `gorm:"column:template_id;type:bigint;primaryKey;autoIncrement:true;comment:主键id" json:"template_id"`
	ImageName     string `gorm:"column:image_name;type:varchar(256);not null;comment:模版对应镜像定位符号" json:"image_name"`
	TemplateLabel string `gorm:"column:template_label;type:varchar(128);not null;comment:模板标签" json:"template_label"`
}

// TableName Template's table name
func (*Template) TableName() string {
	return TableNameTemplate
}
