// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTrigger = "triggers"

// Trigger mapped from table <triggers>
type Trigger struct {
	TriggerID     int64   `gorm:"column:trigger_id;type:bigint;primaryKey;autoIncrement:true;comment:触发器主键" json:"trigger_id"`
	TriggerType   string  `gorm:"column:trigger_type;type:varchar(64);not null;comment:触发器类型" json:"trigger_type"`
	TriggerConfig string  `gorm:"column:trigger_config;type:text;not null;comment:触发器配置信息" json:"trigger_config"`
	TriggerLabel  *string `gorm:"column:trigger_label;type:varchar(256);comment:触发器标签" json:"trigger_label"`
	UserID        *int64  `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`
}

// TableName Trigger's table name
func (*Trigger) TableName() string {
	return TableNameTrigger
}
