// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserUser = "user_user"

// UserUser mapped from table <user_user>
type UserUser struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	LastLogin   *time.Time `gorm:"column:last_login;type:datetime(6)" json:"last_login"`
	IsSuperuser bool       `gorm:"column:is_superuser;type:tinyint(1);not null" json:"is_superuser"`
	FirstName   string     `gorm:"column:first_name;type:varchar(150);not null" json:"first_name"`
	LastName    string     `gorm:"column:last_name;type:varchar(150);not null" json:"last_name"`
	IsStaff     bool       `gorm:"column:is_staff;type:tinyint(1);not null" json:"is_staff"`
	IsActive    bool       `gorm:"column:is_active;type:tinyint(1);not null" json:"is_active"`
	//DateJoined  time.Time  `gorm:"column:date_joined;type:datetime(6);not null" json:"date_joined"`
	Username string `gorm:"column:username;type:varchar(16);not null" json:"username"`
	Password string `gorm:"column:password;type:varchar(256);not null" json:"password"`
	Email    string `gorm:"column:email;type:varchar(32);not null" json:"email"`
	Avatar   string `gorm:"column:avatar;type:varchar(4);not null" json:"avatar"`
}

// TableName UserUser's table name
func (*UserUser) TableName() string {
	return TableNameUserUser
}
